### ISSUE TITLE
Cargo Build Failed

### ISSUE THREAD

**Issue by r4sk01** [hkbudb/vchain-plus#2] opened 2022-12-12 18:29 UTC
`cargo build --release` failed:

```
Compiling vchain-plus v0.1.0 (/home/andrei/Documents/vchain-plus/vchain-plus)
error: invalid format string: expected `'}'`, found `'^'`
   --> src/acc/ops.rs:126:34
    |
126 |             "e(A, B) != e(I, h^{y^q}) * e(Q_{x,y}, h)"
    |                                - ^ expected `}` in format string
    |                                |
    |                                because of this opening brace
    |
    = note: if you intended to print `{`, you can escape it using `{{`

error: invalid format string: expected `'}'`, found `','`
   --> src/acc/ops.rs:134:20
    |
134 |             "e(Q_{x,y}, h^{delta}) != e(Q_{x,y,delta}, h)"
    |                  - ^ expected `}` in format string
    |                  |
    |                  because of this opening brace
    |
    = note: if you intended to print `{`, you can escape it using `{{`

error: invalid format string: expected `'}'`, found `','`
   --> src/acc/ops.rs:232:31
    |
232 |             "e(g^{gamma}, R_{r,s}) != e(R_{r,s,gamma}, h)"
    |                             - ^ expected `}` in format string
    |                             |
    |                             because of this opening brace
    |
    = note: if you intended to print `{`, you can escape it using `{{`

error: invalid format string: expected `'}'`, found `','`
   --> src/acc/ops.rs:236:31
    |
236 |             "e(g^{gamma}, R_{s,r}) != e(R_{s,r,gamma}, h)"
    |                             - ^ expected `}` in format string
    |                             |
    |                             because of this opening brace
    |
    = note: if you intended to print `{`, you can escape it using `{{`

error: invalid format string: expected `'}'`, found `','`
   --> src/acc/ops.rs:244:39
    |
244 |             "e(R_{r}, h) * e(g, 1/R_{r,s}) != e(Z_{s,r}, h^{s-1})"
    |                                     - ^ expected `}` in format string
    |                                     |
    |                                     because of this opening brace
    |
    = note: if you intended to print `{`, you can escape it using `{{`

error: invalid format string: expected `'}'`, found `','`
   --> src/acc/ops.rs:251:39
    |
251 |             "e(R_{s}, h) * e(g, 1/R_{s,r}) != e(Z_{r,s}, h^{r-1})"
    |                                     - ^ expected `}` in format string
    |                                     |
    |                                     because of this opening brace
    |
    = note: if you intended to print `{`, you can escape it using `{{`

error[E0425]: cannot find value `beta` in this scope
   --> src/acc/ops.rs:130:22
    |
130 |             "e(I, h^{beta}) != e(I_{beta}, h)"
    |                      ^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `vchain-plus` due to 7 previous errors

```

How to make it run?

**Comment by haixin-wang** [comment] 2023-01-12 12:17
The error is caused by the new version of anyhow crate. The issue should have been fixed in the latest push.

**Closed as completed** 2023-01-13 02:09 UTC
